// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf56CGq5cPhfLNJua9FCC_oilkKYWZQy0',
    appId: '1:340189664903:web:ff6b5db0ae94701df88a22',
    messagingSenderId: '340189664903',
    projectId: 'auth-testing-39859',
    authDomain: 'auth-testing-39859.firebaseapp.com',
    storageBucket: 'auth-testing-39859.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvBQdG9FxkV_1m9QZeF6VphtdZJIlG10',
    appId: '1:340189664903:android:a02ba4ee3cd43922f88a22',
    messagingSenderId: '340189664903',
    projectId: 'auth-testing-39859',
    storageBucket: 'auth-testing-39859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWaA4YZUA7uEz31wiv2k7nHJYdPN-uNg',
    appId: '1:340189664903:ios:67083b6de31bc15ef88a22',
    messagingSenderId: '340189664903',
    projectId: 'auth-testing-39859',
    storageBucket: 'auth-testing-39859.firebasestorage.app',
    iosBundleId: 'com.example.authTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWaA4YZUA7uEz31wiv2k7nHJYdPN-uNg',
    appId: '1:340189664903:ios:67083b6de31bc15ef88a22',
    messagingSenderId: '340189664903',
    projectId: 'auth-testing-39859',
    storageBucket: 'auth-testing-39859.firebasestorage.app',
    iosBundleId: 'com.example.authTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf56CGq5cPhfLNJua9FCC_oilkKYWZQy0',
    appId: '1:340189664903:web:d23932658e750aacf88a22',
    messagingSenderId: '340189664903',
    projectId: 'auth-testing-39859',
    authDomain: 'auth-testing-39859.firebaseapp.com',
    storageBucket: 'auth-testing-39859.firebasestorage.app',
  );
}
